spring:
  application:
    name: hello-world

server:
  port: 8081
message: Hello World!
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    instance:
      hostname: localhost
